steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-test-image'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant-test:${SHORT_SHA}',
    '-f', 'src/deployment/dockerfile',
    '--target', 'test',
    '.'
  ]

- name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant-test:${SHORT_SHA}'
  id: 'run-unit-tests'
  args: ['npm', 'run', 'test:unit']

- name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant-test:${SHORT_SHA}'
  id: 'run-integration-tests'
  args: ['npm', 'run', 'test:integration']

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-production-image'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant:${SHORT_SHA}',
    '-f', 'src/deployment/dockerfile',
    '--target', 'production',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-production-image'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant:${SHORT_SHA}']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy-cloud-run'
  args: [
    'run', 'deploy', 'receipt-assistant',
    '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant:${SHORT_SHA}',
    '--region', '${_REGION}',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]

substitutions:
  _REGION: 'asia-northeast1'
  _REPOSITORY: 'receipt-assistant'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/receipt-assistant:${SHORT_SHA}'